import type { Prisma } from "@prisma/client";

export const LISTING_CARD_SELECT = {
  id: true,
  mlsId: true,
  mlsSource: true,
  listingId: true,
  imageUrl: true,
  address: true,
  city: true,
  state: true,
  zip: true,
  price: true,
  closePrice: true,
  status: true,
  beds: true,
  baths: true,
  sqft: true,
  listingAgentName: true,
  listingOfficeName: true,
} satisfies Prisma.ListingSelect;

export type ListingCardRow = Prisma.ListingGetPayload<{
  select: typeof LISTING_CARD_SELECT;
}>;

export const LISTING_PROPERTY_SELECT = {
  id: true,
  mlsId: true,
  mlsSource: true,
  tags: true,
  listingId: true,
  price: true,
  closePrice: true,
  originalListPrice: true,
  address: true,
  city: true,
  state: true,
  zip: true,
  county: true,
  subdivision: true,
  beds: true,
  baths: true,
  sqft: true,
  garageSpaces: true,
  propertyType: true,
  status: true,
  imageUrl: true,
  daysOnMarket: true,
  description: true,
  photos: true,
  yearBuilt: true,
  lotSize: true,
  latitude: true,
  longitude: true,
  hoaFee: true,
  hoaFrequency: true,
  taxAmount: true,
  taxYear: true,
  hasPool: true,
  hasWaterfront: true,
  hasGarage: true,
  isNewConstruction: true,
  hasGatedCommunity: true,
  openHouseSchedule: true,
  schoolDistrict: true,
  elementarySchool: true,
  middleSchool: true,
  highSchool: true,
  listingAgentName: true,
  listingAgentMlsId: true,
  listingAgentPhone: true,
  listingAgentEmail: true,
  listingOfficeName: true,
  listingOfficeMlsId: true,
  walkScore: true,
  transitScore: true,
  bikeScore: true,
  featured: true,
  virtualTourUrl: true,
  listDate: true,
  closeDate: true,
  remarks: true,
} satisfies Prisma.ListingSelect;

export type ListingPropertyRow = Prisma.ListingGetPayload<{
  select: typeof LISTING_PROPERTY_SELECT;
}>;
