import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

interface SeedListing {
  mlsId: string;
  address: string;
  city: string;
  zip: string;
  price: number;
  beds: number;
  bathsFull: number;
  bathsHalf: number;
  baths: number;
  sqft: number;
  garageSpaces: number;
  propertyType: string;
  status: string;
  imageUrl: string;
  daysOnMarket: number;
  featured: boolean;
  latitude: number;
  longitude: number;
  yearBuilt: number;
  lotSize: number;
  description: string;
}

const SEED_LISTINGS: SeedListing[] = [
  {
    mlsId: "SEED-001",
    address: "412 Interlachen Ave",
    city: "Winter Park",
    zip: "32789",
    price: 875000,
    beds: 5,
    bathsFull: 3,
    bathsHalf: 2,
    baths: 4,
    sqft: 3850,
    garageSpaces: 2,
    propertyType: "Single Family",
    status: "Active",
    imageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=75",
    daysOnMarket: 3,
    featured: true,
    latitude: 28.5994,
    longitude: -81.3500,
    yearBuilt: 2018,
    lotSize: 0.35,
    description: "Stunning 5-bedroom estate in the heart of Winter Park. Features a chef's kitchen, heated pool, and lush tropical landscaping. Walking distance to Park Avenue shops and restaurants.",
  },
  {
    mlsId: "SEED-002",
    address: "9201 Cypress Ridge Ct",
    city: "Windermere",
    zip: "34786",
    price: 785000,
    beds: 4,
    bathsFull: 3,
    bathsHalf: 1,
    baths: 3.5,
    sqft: 3240,
    garageSpaces: 2,
    propertyType: "Single Family",
    status: "Active",
    imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=75",
    daysOnMarket: 18,
    featured: true,
    latitude: 28.4958,
    longitude: -81.5328,
    yearBuilt: 2015,
    lotSize: 0.28,
    description: "Elegant lakefront home in Windermere with panoramic water views. Open floor plan, gourmet kitchen, and resort-style pool. Located in top-rated school district.",
  },
  {
    mlsId: "SEED-003",
    address: "3714 Woodbury Dr",
    city: "Oviedo",
    zip: "32765",
    price: 545000,
    beds: 4,
    bathsFull: 3,
    bathsHalf: 0,
    baths: 3,
    sqft: 2680,
    garageSpaces: 2,
    propertyType: "Single Family",
    status: "Active",
    imageUrl: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=75",
    daysOnMarket: 7,
    featured: true,
    latitude: 28.6700,
    longitude: -81.2081,
    yearBuilt: 2020,
    lotSize: 0.22,
    description: "Modern 4-bedroom home in Oviedo's premier community. Smart home features, energy-efficient design, and a spacious backyard perfect for entertaining.",
  },
  {
    mlsId: "SEED-004",
    address: "1830 Timacuan Blvd",
    city: "Lake Mary",
    zip: "32746",
    price: 495000,
    beds: 4,
    bathsFull: 2,
    bathsHalf: 1,
    baths: 2.5,
    sqft: 2420,
    garageSpaces: 2,
    propertyType: "Single Family",
    status: "Active",
    imageUrl: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=75",
    daysOnMarket: 22,
    featured: true,
    latitude: 28.7589,
    longitude: -81.3178,
    yearBuilt: 2012,
    lotSize: 0.25,
    description: "Beautiful family home in Timacuan golf community. Upgraded kitchen, wood floors throughout, and screened lanai overlooking the 14th fairway.",
  },
  {
    mlsId: "SEED-005",
    address: "2847 Lakeside Blvd",
    city: "Orlando",
    zip: "32801",
    price: 485000,
    beds: 4,
    bathsFull: 3,
    bathsHalf: 0,
    baths: 3,
    sqft: 2340,
    garageSpaces: 2,
    propertyType: "Single Family",
    status: "Pending",
    imageUrl: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=800&q=75",
    daysOnMarket: 14,
    featured: false,
    latitude: 28.5383,
    longitude: -81.3792,
    yearBuilt: 2016,
    lotSize: 0.18,
    description: "Charming lakeside home in downtown Orlando. Updated interiors with quartz countertops, walk-in closets, and a private dock on Lake Davis.",
  },
  {
    mlsId: "SEED-006",
    address: "651 Celebration Ave",
    city: "Celebration",
    zip: "34747",
    price: 425000,
    beds: 3,
    bathsFull: 2,
    bathsHalf: 1,
    baths: 2.5,
    sqft: 1980,
    garageSpaces: 1,
    propertyType: "Villa",
    status: "Active",
    imageUrl: "https://images.unsplash.com/photo-1576941089067-2de3c901e126?auto=format&fit=crop&w=800&q=75",
    daysOnMarket: 31,
    featured: false,
    latitude: 28.3253,
    longitude: -81.5339,
    yearBuilt: 2005,
    lotSize: 0.12,
    description: "Disney-adjacent villa in the charming town of Celebration. Maintenance-free living with community pools, walking trails, and top-rated schools.",
  },
  {
    mlsId: "SEED-007",
    address: "4522 Sunridge Ln",
    city: "Clermont",
    zip: "34711",
    price: 420000,
    beds: 3,
    bathsFull: 2,
    bathsHalf: 0,
    baths: 2,
    sqft: 1890,
    garageSpaces: 2,
    propertyType: "Single Family",
    status: "Active",
    imageUrl: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=800&q=75",
    daysOnMarket: 2,
    featured: false,
    latitude: 28.5494,
    longitude: -81.7729,
    yearBuilt: 2022,
    lotSize: 0.20,
    description: "Brand new construction in Clermont's rolling hills. Open concept living, covered patio with sunset views, and energy-efficient features throughout.",
  },
  {
    mlsId: "SEED-008",
    address: "2103 Rock Springs Rd",
    city: "Apopka",
    zip: "32712",
    price: 388000,
    beds: 3,
    bathsFull: 2,
    bathsHalf: 0,
    baths: 2,
    sqft: 1760,
    garageSpaces: 2,
    propertyType: "Single Family",
    status: "Active",
    imageUrl: "https://images.unsplash.com/photo-1523217582562-09d0def993a6?auto=format&fit=crop&w=800&q=75",
    daysOnMarket: 45,
    featured: false,
    latitude: 28.6764,
    longitude: -81.5081,
    yearBuilt: 2008,
    lotSize: 0.30,
    description: "Spacious home near Wekiwa Springs State Park. Large fenced yard, updated bathrooms, and a two-car garage with workshop space.",
  },
  {
    mlsId: "SEED-009",
    address: "817 Magnolia Park Blvd",
    city: "Sanford",
    zip: "32771",
    price: 362000,
    beds: 3,
    bathsFull: 2,
    bathsHalf: 0,
    baths: 2,
    sqft: 1640,
    garageSpaces: 2,
    propertyType: "Single Family",
    status: "Active",
    imageUrl: "https://images.unsplash.com/photo-1449844908441-8829872d2607?auto=format&fit=crop&w=800&q=75",
    daysOnMarket: 29,
    featured: false,
    latitude: 28.8003,
    longitude: -81.2733,
    yearBuilt: 2010,
    lotSize: 0.18,
    description: "Well-maintained home in Sanford's historic district. Close to the Riverwalk, local restaurants, and the SunRail station for easy commuting.",
  },
  {
    mlsId: "SEED-010",
    address: "5040 Elkcam Blvd",
    city: "Deltona",
    zip: "32725",
    price: 310000,
    beds: 3,
    bathsFull: 2,
    bathsHalf: 0,
    baths: 2,
    sqft: 1480,
    garageSpaces: 2,
    propertyType: "Single Family",
    status: "Pending",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=75",
    daysOnMarket: 8,
    featured: false,
    latitude: 28.9005,
    longitude: -81.2136,
    yearBuilt: 2006,
    lotSize: 0.22,
    description: "Move-in ready home in Deltona. New roof, freshly painted interior, and a screened porch overlooking a private backyard.",
  },
  {
    mlsId: "SEED-011",
    address: "3302 Mariana Way",
    city: "Kissimmee",
    zip: "34741",
    price: 285000,
    beds: 3,
    bathsFull: 2,
    bathsHalf: 1,
    baths: 2.5,
    sqft: 1560,
    garageSpaces: 1,
    propertyType: "Townhome",
    status: "Active",
    imageUrl: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=800&q=75",
    daysOnMarket: 55,
    featured: false,
    latitude: 28.2919,
    longitude: -81.4076,
    yearBuilt: 2014,
    lotSize: 0.06,
    description: "Modern townhome minutes from Disney. End unit with extra windows, attached garage, and community pool and fitness center.",
  },
  {
    mlsId: "SEED-012",
    address: "2201 S Atlantic Ave #408",
    city: "Daytona Beach",
    zip: "32118",
    price: 275000,
    beds: 2,
    bathsFull: 2,
    bathsHalf: 0,
    baths: 2,
    sqft: 1120,
    garageSpaces: 0,
    propertyType: "Condo",
    status: "Active",
    imageUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=75",
    daysOnMarket: 38,
    featured: false,
    latitude: 29.2108,
    longitude: -81.0059,
    yearBuilt: 2002,
    lotSize: 0,
    description: "Oceanfront condo with stunning Atlantic views. Updated kitchen, impact windows, and building amenities include pool, gym, and beach access.",
  },
];

async function main() {
  console.log("Seeding listings...");

  for (const listing of SEED_LISTINGS) {
    await prisma.listing.upsert({
      where: { mlsId: listing.mlsId },
      update: {
        price: listing.price,
        address: listing.address,
        city: listing.city,
        zip: listing.zip,
        beds: listing.beds,
        bathsFull: listing.bathsFull,
        bathsHalf: listing.bathsHalf,
        baths: listing.baths,
        sqft: listing.sqft,
        garageSpaces: listing.garageSpaces,
        hasGarage: listing.garageSpaces > 0,
        propertyType: listing.propertyType,
        status: listing.status,
        imageUrl: listing.imageUrl,
        daysOnMarket: listing.daysOnMarket,
        featured: listing.featured,
        latitude: listing.latitude,
        longitude: listing.longitude,
        yearBuilt: listing.yearBuilt,
        lotSize: listing.lotSize,
        description: listing.description,
      },
      create: {
        mlsId: listing.mlsId,
        price: listing.price,
        address: listing.address,
        city: listing.city,
        zip: listing.zip,
        beds: listing.beds,
        bathsFull: listing.bathsFull,
        bathsHalf: listing.bathsHalf,
        baths: listing.baths,
        sqft: listing.sqft,
        garageSpaces: listing.garageSpaces,
        hasGarage: listing.garageSpaces > 0,
        propertyType: listing.propertyType,
        status: listing.status,
        imageUrl: listing.imageUrl,
        daysOnMarket: listing.daysOnMarket,
        featured: listing.featured,
        latitude: listing.latitude,
        longitude: listing.longitude,
        yearBuilt: listing.yearBuilt,
        lotSize: listing.lotSize,
        description: listing.description,
      },
    });
    console.log(`  Upserted: ${listing.address}, ${listing.city}`);
  }

  console.log(`Seeded ${SEED_LISTINGS.length} listings.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
